lm_name: 7b_orca
max_length: 64
num_beams: 5
length_penalty: -2
no_repeat_ngram_size: 2
fluency_alpha: 0.3
fluency_threshold: 0.0
visual_threshold: 0.05
prefix_lm: "the"
prefix_vm: "the"
lower_text: True
