lm_name: 7b_orca
max_length: 64
num_beams: 1
length_penalty: 0
fluency_alpha: 0.5
fluency_threshold: 0.0001
visual_threshold: 0.000001
instruction_lm: "Do not say 'it depends' and provide a single definitive answer. Do not say 'However'. Explain your answer given the image.\n\"{}\""
instruction_vm: "Do not say 'it depends' and provide a single definitive answer. Do not say 'However'. Explain your answer given the image.\n\"{}\""
prefix_lm: " the"
prefix_vm: " the"
lower_text: False
