max_length: 64
num_beams: 5
length_penalty: -2
no_repeat_ngram_size: 2
fluency_alpha: 0.4
fluency_threshold: 0.00001
visual_threshold: 0.001
# instruction_vm: " Give a short answer."
instruction_lm: "Answer the question given the image. Give your best guess, even if you're not sure. Do not say 'it is difficult to answer' and provide clear answer. {}"
prefix_lm: "The answer is"
prefix_vm: "The answer is"
lower_text: True
do_cot: True
