max_length: 64
fluency_alpha: 0.4
fluency_threshold: 0.00001
visual_threshold: 0.01
instruction_lm: "Answer the question given the image. Give your best guess, even if you're not sure. "
prefix_lm: "The answer is"
prefix_vm: "The answer is"
num_beams: 5
